# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 12
#$ -q sThC.q
#$ -l mres=12G,h_data=1G,h_vmem=1G
#$ -cwd
#$ -j y
#$ -N <SAMPLE>
#$ -o logs/<SAMPLE>.log
#
# ----------------Modules------------------------- #
# 
module load bio/seqkit
module load tools/conda
start-conda
source activate flye
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
raw="$1"
sample="$2"
name="$3"
results="$4"
#
flye \
--nano-hq \
${raw}/${sample} \
--iterations 3 \
--min-overlap 1000 \
--out-dir ${results}/flye/${name} \
-t $NSLOTS
#
# This copies the hydra job log into the flye_assemblies directory
cp ${results}/../../jobs/logs/${name}_flye.log ${results}/flye_assemblies/${name}_flye_hydra.log

# Here we test to see if there is the file labeled "assembly.fasta" in the flye
# results folder, then copiy them into a flye_assemblies folder. We do the same
# for the program log. 
if
  [[ -f "${results}/flye/${name}/flye.log" ]];
then
  cp -r ${results}/flye/${name}/flye.log \
  ${results}/flye_assemblies/${name}_flye.log
fi

if
  [[ -f "${results}/flye/${name}/assembly.fasta" ]]; \
then
  cp -r ${results}/flye/${name}/assembly.fasta \
  ${results}/flye_assemblies/${name}_flye_assembly.fasta
  cp -r ${results}/flye/${name}/assembly_info.txt \
  ${results}/flye_assemblies/${name}_assembly_info.txt
  cp -r ${results}/flye/${name}/assembly_graph.gfa \
    ${results}/flye_assemblies/${name}_flye_assembly_graph.gfa
fi
#
echo = `date` job $JOB_NAME done