# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 12
#$ -q mThM.q
#$ -l mres=120G,h_data=10G,h_vmem=10G,himem
#$ -cwd
#$ -j y
#$ -N <SAMPLE>
#$ -o logs/<SAMPLE>.log
#
# ----------------Modules------------------------- #
# 
module load module-verbose
module load bio/seqkit
module load tools/conda
start-conda
source activate flye
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
raw="$1"
sample="$2"
name="$3"
results="$4"
#
flye \
--nano-hq \
${raw}/${sample} \
--iterations 3 \
--min-overlap 1000 \
--out-dir ${results}/flye/${name} \
-t $NSLOTS
#
# This copies the hydra job log into the flye_assemblies directory
cp ${results}/../../jobs/logs/${name}_flye_hydra.log \
${results}/flye_assemblies/${name}_flye_hydra.log

if
  [[ -f "${results}/flye/${name}/flye.log" ]]; then \
  cp -r ${results}/flye/${name}/flye.log \
  ${results}/flye_assemblies/${name}_flye.log
fi

if
  [[ -f "${results}/flye/${name}/assembly.fasta" ]]; then \
  cp ${results}/flye/${name}/assembly_info.txt \
  ${results}/flye_assemblies/${name}_flye_assembly_info.txt
  cp ${results}/flye/${name}/assembly_graph.gfa \
  ${results}/flye_assemblies/${name}_flye_assembly_graph.gfa
  cp ${results}/flye/${name}/assembly.fasta \
  ${results}/flye_assemblies/${name}_flye_assembly.fasta
  seqkit seq ${results}/flye/${name}/assembly.fasta \
  --max-len 22000 --min-len 1000 -w 0 \
  -o ${results}/flye_assemblies/${name}_flye_assembly_mito_filtered.fasta
fi
# Here we test to see if there is the file labeled "assembly.fasta" in the flye
# results folder, then copiy them into a flye_assemblies folder. We do the same
# for the program log. 
#

echo = `date` job $JOB_NAME done