#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 20
#$ -q mThC.q
#$ -l mres=40G,h_data=2G,h_vmem=32G
#$ -cwd
#$ -j y
#$ -N ${sample}
#$ -o logs/${sample}_mitofinder.log
#
# ----------------Modules------------------------- #
module load module-verbose
module load tools/conda
start-conda
source activate medaka
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
assemblies="$1"
raw_nanopore="$2"
sample="$3"
name="$4"
results="$5"
#
medaka_consensus \
-d ${assemblies}/${sample} \
-i ${raw_nanopore}/${name}_trimmed_filtered.fastq.gz \
-o ${results}/medaka/${name} \
-m r1041_e82_400bps_hac_v4.3.0 \
-t $NSLOTS
#
cp ${results}/../../jobs/logs/${name}_medaka_hydra.log ${results}/medaka_corrected_assemblies/${name}_medaka_hydra.log
#
if
  [[ -f "${results}/medaka/${name}/consensus.fasta" ]]; \
then
  cp -r ${results}/medaka/${name}/consensus.fasta \
  ${results}/medaka_corrected_assemblies/${name}_medaka_consensus.fasta
fi

#
echo = `date` job $JOB_NAME done

