#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 4
#$ -q sThC.q
#$ -l mres=24G,h_data=6G,h_vmem=32G
#$ -cwd
#$ -j y
#$ -N null
#$ -o null
#
# ----------------Modules------------------------- #
module load module-verbose
module load tools/conda
start-conda
source activate nanoplot
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
reads="$1"
sample="$2"
name="$3"
data="$4"
nanoplot_results="$5"
#
NanoPlot \
--fastq ${reads}/${sample} \
--outdir ${nanoplot_results}/${name} \
--no_static \
--title ${name} \
--threads $NSLOTS

#
cp logs/${name}_nanoplot_hydra.log \
${nanoplot_results}/${name}_nanoplot_hydra.log

test -f ${nanoplot_results}/${name}/NanoPlot-report.html \
&& cp  ${nanoplot_results}/${name}/NanoPlot-report.html ${nanoplot_results}/${name}_NanoPlot-report.html \
&& cp ${nanoplot_results}/${name}/*.log ${nanoplot_results}/${name}_nanoplot.log \
&& cp ${nanoplot_results}/${name}/NanoStats.txt ${nanoplot_results}/${name}_nanoplot_stats.txt 
#
echo = `date` job $JOB_NAME done

# This job file loads the conda module, activates the nanoplot
# environment, and runs nanoplot on all samples.
# -o is the path to the output directory