#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 4
#$ -q sThC.q
#$ -l mres=16G,h_data=4G,h_vmem=16G
#$ -cwd
#$ -j y
#$ -N null
#$ -o null
#
# ----------------Modules------------------------- #
module load tools/conda
start-conda
source activate nanoplot
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
raw="$1"
sample="$2"
name="$3"
data="$4"
#
NanoPlot \
--fastq ${raw}/${sample} \
--outdir ${data}/results/nanoplot_analyses/${name} \
--no_static \
--title ${name} \
--threads $NSLOTS

#
cp ${raw}/../../jobs/logs/${name}_nanoplot_hydra.log \
${data}/results/nanoplot_analyses/${name}_nanoplot_hydra.log

test -f ${data}/results/nanoplot_analyses/${name}/NanoPlot-report.html \
&& cp  ${data}/results/nanoplot_analyses/${name}/NanoPlot-report.html ${data}/results/nanoplot_analyses/${name}_NanoPlot-report.html \
&& cp ${data}/results/nanoplot_analyses/${name}/*.log ${data}/results/nanoplot_analyses/${name}_nanoplot.log \
&& cp ${data}/results/nanoplot_analyses/${name}/NanoStats.txt ${data}/results/${name}_nanoplot_stats.txt 
#
echo = `date` job $JOB_NAME done

# This job file loads the conda module, activates the nanoplot
# environment, and runs nanoplot on all samples.
# -o is the path to the output directory