#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 8
#$ -q sThC.q
#$ -l mres=64G,h_data=8G,h_vmem=48G
#$ -cwd
#$ -j y
#$ -N null
#$ -o null
#
# ----------------Modules------------------------- #
module load module-verbose
module load tools/conda
start-conda
source activate toulligqc
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
raw="$1"
sample="$2"
name="$3"
data="$4"
toulligqc_results="$5"
#
toulligqc \
--fastq ${raw}/${sample} \
--report-name ${name}_toulligqc \
--thread $NSLOTS \
--html-report-path ${toulligqc_results}/${name}_toulligqc_report.html
#
cp logs/${name}_toulligqc_hydra.log \
${toulligqc_results}/${name}_toulligqc_hydra.log
#
echo = `date` job $JOB_NAME done

# This job file loads the conda module, activates the toulligqc
# environment, and runs toulligqc on all samples.

