#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 2
#$ -q sThC.q
#$ -l mres=4G,h_data=2G,h_vmem=2G
#$ -cwd
#$ -j y
#$ -N PROJECT_trim
#$ -o logs/PROJECT_trim.log
#
# ----------------Modules------------------------- #
module load tools/conda
start-conda
source activate chopper
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
raw="$1"
data="$2"
name="$3"

#
chopper \
--headcrop 11 \
--tailcrop 10 \
--threads $NSLOTS \
--input ${raw}/${name}.fastq.gz \
| gzip > ${data}/trimmed_reads_nanopore/${name}_trimmed.fastq.gz

#
echo = `date` job $JOB_NAME done

# This job file loads the conda module, activates the chopper environment,
# and runs chopper to trim and/or filter raw nanopore reads.

# These are the commands given to chopper, with a brief description. For 
# more information please see the manual:
# https://github.com/wdecoster/chopper/
# --headcrop: how many nucleotides to trim from the start of each read
# --tailcrop: how many nucleotides to trim from the end of each read
# --threads: number of CPUs to use
# --input: the name of the nanopore raw read file (*.fastq.gz)
# the last line pipes the results to gzip to re-compress output and names it


