#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -q sThM.q
#$ -l mres=24G,h_data=24G,h_vmem=48G,himem
#$ -cwd
#$ -j y
#$ -N null
#$ -o null
#
# ----------------Modules------------------------- #
module load tools/conda
start-conda
source activate nanoqcenv
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
raw="$1"
sample="$2"
name="$3"
#
nanoQC \
--outdir ${raw}/nanoqc_analyses/${name} \
${raw}/${sample}
#
cp ${raw}/../../jobs/logs/${name}_nanoqc_hydra.log \
${raw}/nanoqc_analyses/${name}_nanoqc_hydra.log

test -f ${raw}/nanoqc_analyses/${name}/NanoQC.log \
&& cp  ${raw}/nanoqc_analyses/${name}/NanoQC.log \
${raw}/nanoqc_analyses/${name}_NanoQC.log

test -f ${raw}/nanoqc_analyses/${name}/nanoQC.html \
&& cp  ${raw}/nanoqc_analyses/${name}/nanoQC.html \
${raw}/nanoqc_analyses/${name}_NanoQC.html
#
echo = `date` job $JOB_NAME done

# This job file loads the conda module, activates the nanoqc
# environment, and runs nanoqc on all samples.
# --outdir is the path to the output directory
# the second line is the path to the sequence to be analyzed
