#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 8
#$ -q sThC.q
#$ -l mres=64G,h_data=8G,h_vmem=32G
#$ -cwd
#$ -j y
#$ -N null
#$ -o null
#
# ----------------Modules------------------------- #
module load tools/conda
start-conda
source activate toulligqc
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
raw="$1"
sample="$2"
name="$3"
#
toulligqc \
--fastq ${raw}/${sample} \
--report-name ${name}_toulligqc \
--thread $NSLOTS \
--html-report-path ${raw}/toulligqc_analyses/${name}_Toulligqc-report.html
#
cp ${raw}/../../jobs/logs/${name}_toulligqc_hydra.log \
${raw}/toulligqc_analyses/${name}_toulligqc_hydra.log
#
echo = `date` job $JOB_NAME done

# This job file loads the conda module, activates the toulligqc
# environment, and runs toulligqc on all samples.

# --fastq is the name of the input file, in fastq.gz format
# --report-name the name of the report so that it isn't a generic "report.txt"
# --thread the number of CPUs
# --html-report-path the path to the directory for the output file
