# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -q sThC.q
#$ -l mres=2G,h_data=2G,h_vmem=2G
#$ -cwd
#$ -j y
#$ -N project
#$ -o project.log
#
# ----------------Modules------------------------- #

#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
#!/bin/bash
contigs="$1"
name="$2"
sample="$3"
results="$4"


input_file=${contigs}${sample}
output_file=${results}/${name}"_spades_contigs_possible_circular.fasta"

# Clear the output file if it exists
> "$output_file"

awk '
  BEGIN { previous_line = "" }
  {
    line_length = length($0)
    if (line_length >= 500 && line_length <= 10000) {
      first_fifty_chars = substr($0, 1, 50)
      last_fourhundredfifty_chars = substr($0, line_length - 449, 450)
      if (index(last_fourhundredfifty_chars, first_fifty_chars) > 0) {
        print previous_line >> "'"$output_file"'"
        print $0 >> "'"$output_file"'"
      }
    }
    previous_line = $0
  }
' "$input_file"

echo "Matching strings have been saved to $output_file" 