#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 8
#$ -q sThC.q
#$ -l mres=8G
#$ -cwd
#$ -j y
#$ -N PROJECT_trim
#$ -o logs/PROJECT_trim.log
#
# ----------------Modules------------------------- #
module load bioinformatics/sratoolkit
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
sra="$1"
data="$2"
sample="$3"

#
vdb-validate ${sra}/${sample}/${sample}.sra

fasterq-dump ${sra}/${sample}/${sample}.sra \
--outdir ${data}/raw \
--threads $NSLOTS --verbose

gzip ${data}/raw/${sample}*.fastq
mv ${data}/raw/${sample}_1.fastq.gz ${data}/raw/${sample}_R1.fastq.gz
mv ${data}/raw/${sample}_2.fastq.gz ${data}/raw/${sample}_R2.fastq.gz
#
echo = `date` job $JOB_NAME done

