#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -q sThM.q
#$ -l mres=48G,h_data=48G,h_vmem=48G,himem
#$ -cwd
#$ -j y
#$ -N ${sample}_mitos
#$ -o logs/${sample}_mitos.log
#
# ----------------Modules------------------------- #
module load bio/mitos
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
contigs="$1"
results="$2"
sample="$3"
name="$4"
taxa="$5"
shortname="$6"
#
runmitos.py \
-i ${contigs}/${sample} \
-c ${taxa} \
-o ${results}/mitos_spades/${name}_mitos_spades \
-r /scratch/nmnh_lab/macdonaldk/ref/refseq89m \
-R /scratch/nmnh_lab/macdonaldk/ref/refseq89m \
--debug
#
echo = `date` job $JOB_NAME done

cp ${results}/../../jobs/logs/${name}_mitos_spades.log \
${results}/mitos_results/${name}_mitos_spades.log

if
  [[ -f "${results}/mitos_spades/${name}_mitos_spades/result.gff" ]]
then
  cp -r ${results}/mitos_spades/${name}_mitos_spades/plots \
  ${results}/mitos_results/${name}_mitos_spades/${shortname}_plots
  cp ${results}/mitos_spades/${name}_mitos_spades/result.bed \
  ${results}/mitos_results/${name}_mitos_spades/${shortname}.bed
  cp ${results}/mitos_spades/${name}_mitos_spades/result.gff \
  ${results}/mitos_results/${name}_mitos_spades/${shortname}.gff
  cp ${results}/mitos_spades/${name}_mitos_spades/result.fas \
  ${results}/mitos_results/${name}_mitos_spades/${shortname}.fas
  cp ${results}/mitos_spades/${name}_mitos_spades/result.faa \
  ${results}/mitos_results/${name}_mitos_spades/${shortname}.faa
  cp ${results}/mitos_spades/${name}_mitos_spades/result.mitos \
  ${results}/mitos_results/${name}_mitos_spades/${shortname}.mitos
  cp ${results}/mitos_spades/${name}_mitos_spades/result.seq \
  ${results}/mitos_results/${name}_mitos_spades/${shortname}.seq
  cp ${results}/mitos_spades/${name}_mitos_spades/result.geneorder \
  ${results}/mitos_results/${name}_mitos_spades/${shortname}.geneorder
  cp ${results}/mitos_spades/${name}_mitos_spades/result.png \
  ${results}/mitos_results/${name}_mitos_spades/${shortname}.png
  cp ${results}/mitos_spades/${name}_mitos_spades/stst.dat \
  ${results}/mitos_results/${name}_mitos_spades/${shortname}stst.dat
else
  echo ${name} >> ${results}/mitos_results/mitos_failures.txt
fi








# -c is the genetic code
# -o is the output directory
# -r is the directory where the reference data is found, relative to -R
# -R is the base directory containing thd reference data
# For -r and -R, I use the same path, and it works. Both should not be
# necessary, but I get an error if both are not included.
# --debug gives a better log output. Typically, little is put into the log,
# especially when there is an error.

# Genetic codes
# 1. The Standard Code 
# 2. The Vertebrate Mitochondrial Code 
# 3. The Yeast Mitochondrial Code 
# 4. The Mold, Protozoan, and Coelenterate Mitochondrial Code and the
#     Mycoplasma/Spiroplasma Code
# 5. The Invertebrate Mitochondrial Code
# 6. The Ciliate, Dasycladacean and Hexamita Nuclear Code 
# 9. The Echinoderm and Flatworm Mitochondrial Code 
# 10. The Euplotid Nuclear Code 
# 11. The Bacterial, Archaeal and Plant Plastid Code 
# 12. The Alternative Yeast Nuclear Code 
# 13. The Ascidian Mitochondrial Code 
# 14. The Alternative Flatworm Mitochondrial Code 
# 16. Chlorophycean Mitochondrial Code 
# 21. Trematode Mitochondrial Code 
# 22. Scenedesmus obliquus Mitochondrial Code 
# 23. Thraustochytrium Mitochondrial Code 
# 24. Pterobranchia Mitochondrial Code 
# 25. Candidate Division SR1 and Gracilibacteria Code