# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 10
#$ -q mThM.q
#$ -l mres=120G,h_data=12G,h_vmem=200G,himem
#$ -l ssd_res=200G -v SSD_SAVE_MAX=0
#$ -cwd
#$ -j y
#$ -N PROJECT_spades
#$ -o logs/PROJECT_spades.log
#
# ----------------Modules------------------------- #
module load tools/ssd
module load bio/spades
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
trimmed="$1"
name="$2"
results="$3"
#
spades.py \
-o ${results}/spades/${name} \
--pe1-1 ${trimmed}/${name}_R1_PE_trimmed.fastq.gz \
--pe1-2 ${trimmed}/${name}_R2_PE_trimmed.fastq.gz \
--pe1-s ${trimmed}/${name}_R0_SE_trimmed.fastq.gz \
-t $NSLOTS --tmp-dir $SSD_DIR

cp ${results}/../../jobs/logs/${name}_spades.log ${results}/spades_contigs/${name}_spades.log

test -f ${results}/spades/${name}/contigs.fasta \
&& cp ${results}/spades/${name}/contigs.fasta ${results}/spades_contigs/${name}_spades_contigs.fasta



#
echo = `date` job $JOB_NAME done

# -o is the path to the directory where you want your results saved
# --pe1-1 is the path to the file of the paired R1 reads of the first paired-end 
# library (you can have mutiple libraries as input files). --pe1-2 is the path
# to the file of the paired R2 reads of the first paired-end library. --pe1-s
# is the path of the unpaired reads (both R1 and R2 should be in the same file)
# of the first paired-end library.
# -t is the number of threads, and -m is the total amount of memory allocated 
# --tmp-dir creates a temporary SSD to hold SPAdes temporary files. SPAdes 
# creates a large number of temporary files, sometimes more than hydra allows.
# This creates a temporary SSD to hold those files so hydra won't kill the
# job. we then remove those files with rm -rf $SSD_DIR/*