#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 2
#$ -q sThC.q
#$ -l mres=4G,h_data=2G,h_vmem=2G
#$ -cwd
#$ -j y
#$ -N PROJECT_trim
#$ -o logs/PROJECT_trim.log
#
# ----------------Modules------------------------- #
module load module-verbose
module load tools/conda
start-conda
source activate chopper
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
trimmed="$1"
sample="$2"
name="$3"
data="$4"
#
gunzip -c ${trimmed}/${sample} \
| chopper \
--quality 8 \
--minlength 100 \
--threads $NSLOTS \
> ${data}/filtered_reads/${name}_trimmed_filtered.fastq
#
gzip -3 ${data}/filtered_reads/${name}_trimmed_filtered.fastq

#
echo = `date` job $JOB_NAME done

# This job file loads the conda module, activates the chopper environment,
# and runs chopper to trim all trimmed reads.

# These are the commands given to chopper, with a brief description. For 
# more information please see the manual:
# https://github.com/wdecoster/chopper/


