#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 6
#$ -q sThC.q
#$ -l mres=6G,h_data=1G,h_vmem=4G
#$ -cwd
#$ -j y
#$ -N ${sample}
#$ -o logs/${sample}_mitofinder.log
#
# ----------------Modules------------------------- #
module load module-verbose
module load bio/minimap2
module load bio/samtools
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
contigs="$1"
filtered_nanopore="$2"
name="$3"
results="$4"
#
if [ -f ${contigs}/${name}_mitofinder_medaka_Final_Results/${name}_*_contig_1.fasta ]; then
  minimap2 \
  -ax map-ont -t $NSLOTS \
  ${contigs}/${name}_mitofinder_medaka_Final_Results/${name}_*_contig_1.fasta \
  ${filtered_nanopore}/${name}_trimmed_filtered.fastq.gz
else
  minimap2 \
  -ax map-ont -t $NSLOTS \
  ${contigs}/${name}_mitofinder_medaka_Final_Results/${name}_*_contig.fasta \
  ${filtered_nanopore}/${name}_trimmed_filtered.fastq.gz
fi | \
samtools view -F 4 -b > \
${results}/minimap_results/${name}_minimap_mitofinder_medaka.bam

#
cp ${results}/../../jobs/logs/${name}_minimap_medaka_hydra.log ${results}/minimap_results/${name}_minimap_medaka_hydra.log

#
echo = `date` job $JOB_NAME done

