#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -q sThC.q
#$ -l mres=6G,h_data=6G,h_vmem=6G
#$ -cwd
#$ -j y
#$ -N null
#$ -o null
#
# ----------------Modules------------------------- #
module load module-verbose
module load bio/fastqc
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
reads="$1"
fastqc_results="$2"
sample="$3"
name="$4"
#
fastqc \
-o ${fastqc_results} \
${reads}/${sample}
#
cp logs/${name}_fastqc_hydra.log \
${fastqc_results}/${name}_fastqc_hydra.log
echo = `date` job $JOB_NAME done

# This job file loads the conda module, activates the fastqc
# environment, and runs fastqc on all samples.
# -o is the path to the output directory
