#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 2
#$ -q sThC.q
#$ -l mres=4G,h_data=2G,h_vmem=64G
#$ -cwd
#$ -j y
#$ -N ${sample}
#$ -o logs/${sample}_mitofinder.log
#
# ----------------Modules------------------------- #
module load module-verbose
module load bioinformatics/mitofinder
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
contigs="$1"
shortname="$2"
taxa="$3"
ref="$4"
sample="$5"
results="$6"

#
mitofinder \
-j ${shortname}_mitofinder_getorganelle \
-o ${taxa} \
-r /scratch/nmnh_lab/macdonaldk/ref/mito_reference_${ref}*.gb \
-a ${contigs}/${sample} \
--new-genes -p $NSLOTS -m 4

cp ${results}/../../jobs/logs/${shortname}_mitofinder_getorganelle_hydra.log \
${results}/mitofinder_results/${shortname}_mitofinder_getorganelle_hydra.log

if [ -f ${results}/mitofinder_getorganelle/${shortname}_mitofinder_getorganelle/${shortname}_mitofinder_getorganelle_MitoFinder.log ]; then
  cp ${results}/mitofinder_getorganelle/${shortname}_mitofinder_getorganelle/${shortname}_mitofinder_getorganelle_MitoFinder.log \
  ${results}/mitofinder_results/${shortname}_mitofinder_getorganelle_MitoFinder.log
fi
if [ -d ${results}/mitofinder_getorganelle/${shortname}_mitofinder_getorganelle/${shortname}_mitofinder_getorganelle_MitoFinder_mitfi_Final_Results ]; then
  cp -r ${results}/mitofinder_getorganelle/${shortname}_mitofinder_getorganelle/${shortname}_mitofinder_getorganelle_MitoFinder_mitfi_Final_Results \
  ${results}/mitofinder_results/${shortname}_mitofinder_getorganelle_Final_Results
fi
#
echo = `date` job $JOB_NAME done






# -a is the fasta file containing the contigs that mitofinder will use to 
# annotate 
# -o is the genetic code to use. The list below is from the mitofinder
# documantation (https://github.com/RemiAllio/MitoFinder/blob/master/README.md).
# -r is the path to the reference database, in genbank (.gb) format. Mitofinder
# documentation (https://github.com/RemiAllio/MitoFinder/blob/master/README.md),
# shows how to create a reference database from NCBI.
# --new-genes denotes that some of the genes in the reference database are not
# one of the "official" genes as determined by mitofinder. This is often true
# if you have downloaded the reference database from genbank, because there are 
# some mispellings in gene names in genbank.

# Genetic codes
# 1. The Standard Code 
# 2. The Vertebrate Mitochondrial Code 
# 3. The Yeast Mitochondrial Code 
# 4. The Mold, Protozoan, and Coelenterate Mitochondrial Code and the
#     Mycoplasma/Spiroplasma Code
# 5. The Invertebrate Mitochondrial Code
# 6. The Ciliate, Dasycladacean and Hexamita Nuclear Code 
# 9. The Echinoderm and Flatworm Mitochondrial Code 
# 10. The Euplotid Nuclear Code 
# 11. The Bacterial, Archaeal and Plant Plastid Code 
# 12. The Alternative Yeast Nuclear Code 
# 13. The Ascidian Mitochondrial Code 
# 14. The Alternative Flatworm Mitochondrial Code 
# 16. Chlorophycean Mitochondrial Code 
# 21. Trematode Mitochondrial Code 
# 22. Scenedesmus obliquus Mitochondrial Code 
# 23. Thraustochytrium Mitochondrial Code 
# 24. Pterobranchia Mitochondrial Code 
# 25. Candidate Division SR1 and Gracilibacteria Code

# Using a more limited reference database greatly reduces run time. For exmaple,
# changing from the full database (14000+ mitogenomes) to just molluscs (<500
# mitogenomes) reduces run time from > 3 hours to < 5 minutes, typically.
# Currently there are 11 taxon-specific databases: 
# "Annelida"
# "Arthropoda"
# "Bryozoa"
# "Cnidaria"
# "Ctenophora"
# "Echinodermata"
# "Mollusca"
# "Nemertea"
# "Porifera"
# "Tunicata"
# "Vertebrata"
# There is one database containing the full Genbank refseq database:
# "Metazoa"
# If your taxa of interest are not in one of these groups, you can either enter
# "Metazoa" to use the entire database or contact me and I can typically create
# your chosen database in short order.