#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 8
#$ -q mThM.q
#$ -l mres=96G,h_data=12G,h_vmem=12G,himem
#$ -cwd
#$ -j y
#$ -N ${sample}
#$ -o logs/${sample}_mitofinder.log
#
# ----------------Modules------------------------- #
module load bioinformatics/mitofinder
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
path="$1"
sample="$2"
reference="$3"
#
mitofinder \
-j ${sample} \
-o 1 \
-r ${reference} \
-1 ${path}/${sample}_R1_PE_trimmed.fastq.gz \
-2 ${path}/${sample}_R2_PE_trimmed.fastq.gz \
--new-genes

#
echo = `date` job $JOB_NAME done


# -1 is the path to the R1 PE trimmed file, -2 is the path to the R2 PE trimmed
#  file. PE files come in pairs, both the R1 and R2 are present. 
# -o is the genetic code to use. The list below is from the mitofinder
# documantation (https://github.com/RemiAllio/MitoFinder/blob/master/README.md).
# -r is the path to the reference database, in genbank (.db) format. Mitofinder
# documentation (https://github.com/RemiAllio/MitoFinder/blob/master/README.md),
# shows how to create a reference database from NCBI.
# --new-genes denotes that some of the genes in the reference database are not
# one of the "official" genes as determined by mitofinder. This is often true
# if you have downloaded the reference database from genbank, because there are 
# some mispellings in gene names in genbank.

# Genetic codes
# 1. The Standard Code 
# 2. The Vertebrate Mitochondrial Code 
# 3. The Yeast Mitochondrial Code 
# 4. The Mold, Protozoan, and Coelenterate Mitochondrial Code and the
#     Mycoplasma/Spiroplasma Code
# 5. The Invertebrate Mitochondrial Code
# 6. The Ciliate, Dasycladacean and Hexamita Nuclear Code 
# 9. The Echinoderm and Flatworm Mitochondrial Code 
# 10. The Euplotid Nuclear Code 
# 11. The Bacterial, Archaeal and Plant Plastid Code 
# 12. The Alternative Yeast Nuclear Code 
# 13. The Ascidian Mitochondrial Code 
# 14. The Alternative Flatworm Mitochondrial Code 
# 16. Chlorophycean Mitochondrial Code 
# 21. Trematode Mitochondrial Code 
# 22. Scenedesmus obliquus Mitochondrial Code 
# 23. Thraustochytrium Mitochondrial Code 
# 24. Pterobranchia Mitochondrial Code 
# 25. Candidate Division SR1 and Gracilibacteria Code
