# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 8
#$ -q mThM.q
#$ -l mres=96G,h_data=12G,h_vmem=12G,himem
#$ -cwd
#$ -j y
#$ -N PROJECT_spades
#$ -o logs/PROJECT_spades.log
#
# ----------------Modules------------------------- #
 module load ~/modulefiles/miniconda
 source activate spades
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
path="$1"
sample="$2"
repath="$3"
#
spades.py \
-o ${repath}/results/spades/${sample} \
--pe1-1 ${path}/${sample}_R1_PE_trimmed.fastq.gz \
--pe1-2 ${path}/${sample}_R2_PE_trimmed.fastq.gz \
--pe1-s ${path}/${sample}_SE_concat.fastq.gz 

#
echo = `date` job $JOB_NAME done

# -1 is followed by the path to the R1 trimmed file, and -2 is followed by the
#  path to the R2 trimmed file.
# -o is where the output folder will be saved.
# -F is the type of organelle you are asking the program to find.
# Don't forget to replace USERNAME with your username, and PROJECT with your
# project name.
