# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 16
#$ -q sThM.q
#$ -l mres=288G,h_data=24G,h_vmem=24G,himim
#$ -cwd
#$ -j y
#$ -N PROJECT_spades
#$ -o logs/PROJECT_spades.log
#
# ----------------Modules------------------------- #
module load tools/conda
start-conda
conda activate /scratch/nmnh_lab/envs/genome_skimming/spades_ksm_16Feb23
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
trimmed="$1"
name="$2"
data="$3"
#
spades.py \
-o ${data}/results/spades/${name} \
--pe1-1 ${trimmed}/${name}_R1_PE_trimmed.fastq.gz \
--pe1-2 ${trimmed}/${name}_R2_PE_trimmed.fastq.gz \
--pe1-s ${trimmed}/${name}_R0_SE_trimmed.fastq.gz \
-t 12 -m 288

#
echo = `date` job $JOB_NAME done

# -o is the path to the directory where you want your results saved
# --pe1-1 is the path to the file of the paired R1 reads of the first paired-end 
# library (you can have mutiple libraries as input files). --pe1-2 is the path
# to the file of the paired R2 reads of the first paired-end library. --pe1-s
# is the path of the unpaired reads (both R1 and R2 should be in the same file)
# of the first paired-end library.
# -t is the number of threads, and -m is the total amount of memory allocated 
