#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -q sThM.q
#$ -l mres=48G,h_data=48G,h_vmem=48G,himem
#$ -cwd
#$ -j y
#$ -N ${sample}_mitos
#$ -o logs/${sample}_mitos.log
#
# ----------------Modules------------------------- #
module load bio/mitos
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
contigs="$1"
results="$2"
sample="$3"
name="$4"
taxa="$5"
shortname="$6"
#
runmitos.py \
-i ${contigs}/${sample} \
-c ${taxa} \
-o ${results}/mitos_getorganelle/${name}_mitos_getorganelle \
-r /scratch/nmnh_lab/macdonaldk/ref/refseq89m \
-R /scratch/nmnh_lab/macdonaldk/ref/refseq89m \
--debug
#


cp ${results}/../../jobs/logs/${name}_mitos_getorganelle_hydra.log \
${results}/mitos_results/${shortname}_mitos_getorganelle_hydra.log

if [[ -f "${results}/mitos_flye/${name}_mitos_flye/result.gff" ]]; then
  echo "There is only a single mitochondrial contig found."
  cp -r ${results}/mitos_flye/${name}_mitos_flye/plots/ \
  ${results}/mitos_results/${name}_mitos_flye/${name}_plots
  cp ${results}/mitos_flye/${name}_mitos_flye/result.bed \
  ${results}/mitos_results/${name}_mitos_flye/${name}.bed
  cp ${results}/mitos_flye/${name}_mitos_flye/result.gff \
  ${results}/mitos_results/${name}_mitos_flye/${name}.gff
  cp ${results}/mitos_flye/${name}_mitos_flye/result.fas \
  ${results}/mitos_results/${name}_mitos_flye/${name}.fas
  cp ${results}/mitos_flye/${name}_mitos_flye/result.faa \
  ${results}/mitos_results/${name}_mitos_flye/${name}.faa
  cp ${results}/mitos_flye/${name}_mitos_flye/result.mitos \
  ${results}/mitos_results/${name}_mitos_flye/${name}.mitos
  cp ${results}/mitos_flye/${name}_mitos_flye/result.seq \
  ${results}/mitos_results/${name}_mitos_flye/${name}.seq
  cp ${results}/mitos_flye/${name}_mitos_flye/result.geneorder \
  ${results}/mitos_results/${name}_mitos_flye/${name}.geneorder
  cp ${results}/mitos_flye/${name}_mitos_flye/result.png \
  ${results}/mitos_results/${name}_mitos_flye/${name}.png
  cp ${results}/mitos_flye/${name}_mitos_flye/stst.dat \
  ${results}/mitos_results/${name}_mitos_flye/${name}stst.dat
elif ls -d [0-9] [1-9][0-9] 2>/dev/null | grep -q '.'; then
  for x in ${results}/mitos_flye/${name}_mitos_flye/*/
  echo "There are multiple mitochondrial contigs found."
  contig_number=`basename ${x}`
  cp -r ${results}/mitos_flye/${name}_mitos_flye/${contig_number}/plots \
  ${results}/mitos_results/${name}_mitos_flye/${name}_${contig_number}_plots
  cp ${results}/mitos_flye/${name}_mitos_flye/${contig_number}/result.bed \
  ${results}/mitos_results/${name}_mitos_flye/${name}_${contig_number}.bed
  cp ${results}/mitos_flye/${name}_mitos_flye/${contig_number}/result.gff \
  ${results}/mitos_results/${name}_mitos_flye/${name}_${contig_number}.gff
  cp ${results}/mitos_flye/${name}_mitos_flye/${contig_number}/result.fas \
  ${results}/mitos_results/${name}_mitos_flye/${name}_${contig_number}.fas
  cp ${results}/mitos_flye/${name}_mitos_flye/${contig_number}/result.faa \
  ${results}/mitos_results/${name}_mitos_flye/${name}_${contig_number}.faa
  cp ${results}/mitos_flye/${name}_mitos_flye/${contig_number}/result.mitos \
  ${results}/mitos_results/${name}_mitos_flye/${name}_${contig_number}.mitos
  cp ${results}/mitos_flye/${name}_mitos_flye/${contig_number}/result.seq \
  ${results}/mitos_results/${name}_mitos_flye/${name}_${contig_number}.seq
  cp ${results}/mitos_flye/${name}_mitos_flye/${contig_number}/result.geneorder \
  ${results}/mitos_results/${name}_mitos_flye/${name}_${contig_number}.geneorder
  cp ${results}/mitos_flye/${name}_mitos_flye/${contig_number}/result.png \
  ${results}/mitos_results/${name}_mitos_flye/${name}_${contig_number}.png
  cp ${results}/mitos_flye/${name}_mitos_flye/${contig_number}/stst.dat \
  ${results}/mitos_results/${name}_mitos_flye/${name}_${contig_number}stst.dat
  done
else echo ${name} >> ${results}/mitos_results/mitos_failures.txt
fi
#
echo = `date` job $JOB_NAME done







# -c is the genetic code
# -o is the output directory
# -r is the directory where the reference data is found, relative to -R
# -R is the base directory containing thd reference data
# For -r and -R, I use the same path, and it works. Both should not be
# necessary, but I get an error if both are not included.
# --debug gives a better log output. Typically, little is put into the log,
# especially when there is an error.

# Genetic codes
# 1. The Standard Code 
# 2. The Vertebrate Mitochondrial Code 
# 3. The Yeast Mitochondrial Code 
# 4. The Mold, Protozoan, and Coelenterate Mitochondrial Code and the
#     Mycoplasma/Spiroplasma Code
# 5. The Invertebrate Mitochondrial Code
# 6. The Ciliate, Dasycladacean and Hexamita Nuclear Code 
# 9. The Echinoderm and Flatworm Mitochondrial Code 
# 10. The Euplotid Nuclear Code 
# 11. The Bacterial, Archaeal and Plant Plastid Code 
# 12. The Alternative Yeast Nuclear Code 
# 13. The Ascidian Mitochondrial Code 
# 14. The Alternative Flatworm Mitochondrial Code 
# 16. Chlorophycean Mitochondrial Code 
# 21. Trematode Mitochondrial Code 
# 22. Scenedesmus obliquus Mitochondrial Code 
# 23. Thraustochytrium Mitochondrial Code 
# 24. Pterobranchia Mitochondrial Code 
# 25. Candidate Division SR1 and Gracilibacteria Code