# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 10
#$ -q mThM.q
#$ -l mres=160G,h_data=16G,h_vmem=16G,himem
#$ -l ssd_res=200G -v SSD_SAVE_MAX=0
#$ -cwd
#$ -j y
#$ -N PROJECT_spades
#$ -o logs/PROJECT_spades.log
#
# ----------------Modules------------------------- #
module load module-verbose
module load bio/seqkit
module load tools/ssd
module load bio/spades
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
trimmed="$1"
name="$2"
results="$3"
#
spades.py \
-o ${results}/spades/${name} \
--pe1-1 ${trimmed}/${name}_R1_PE_trimmed.fastq.gz \
--pe1-2 ${trimmed}/${name}_R2_PE_trimmed.fastq.gz \
--pe1-s ${trimmed}/${name}_R0_SE_trimmed.fastq.gz \
-t $NSLOTS --tmp-dir $SSD_DIR

cp ${results}/../../jobs/logs/${name}_spades_hydra.log \
${results}/spades_contigs/${name}_spades_hydra.log

# Here we test to see if there is the file labeled "contigs.fasta" in the spades
# results folder, then copy them into a spades_contigs folder. However, spades
# outputs fasta files with sequences separated by hard returns, which messes up
# a lot of downstream programs, so the command after "&&" (starting with "awk")
# first outputs each sequence on a single line (see copilot for a
# description how this works).

if [ -f ${results}/spades/${name}/contigs.fasta ]; then
  awk '/^>/ {if (NR!=1) printf("\n"); printf("%s\n",$0); next} {printf("%s",$0);} END {printf("\n");}' \
  ${results}/spades/${name}/contigs.fasta > ${results}/spades_contigs/${name}_spades_contigs.fasta
  seqkit seq ${results}/spades_contigs/${name}_spades_contigs.fasta \
  --max-len 22000 --min-len 1000 -w 0 \
  -o ${results}/spades_contigs/${name}_spades_contigs_mito_filtered.fasta 
fi

if [ test -f ${results}/spades/${name}/spades.log ]; then
  cp ${results}/spades/${name}/spades.log \
  ${results}/spades_contigs/${name}_spades.log
fi
#
echo = `date` job $JOB_NAME done

# -o is the path to the directory where you want your results saved
# --pe1-1 is the path to the file of the paired R1 reads of the first paired-end 
# library (you can have mutiple libraries as input files). --pe1-2 is the path
# to the file of the paired R2 reads of the first paired-end library. --pe1-s
# is the path of the unpaired reads (both R1 and R2 should be in the same file)
# of the first paired-end library.
# -t is the number of threads, and -m is the total amount of memory allocated 
# --tmp-dir creates a temporary SSD to hold SPAdes temporary files. SPAdes 
# creates a large number of temporary files, sometimes more than hydra allows.
# This creates a temporary SSD to hold those files so hydra won't kill the
# job. we then remove those files with rm -rf $SSD_DIR/*